name: Embrace Benefits
favicon: null
layout_spectrum: 0.75647
typography_spectrum: 0.50112
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#adadad'
    - '#2e2e2e'
    - '#848484'
    - '#58b43d'
  brandStrength: 0.6875
  lightness: 0.15863941540010273
  saturation: 0.8637511017732322
  rhythmicContrast: 0.1472227624617517
purpose: []
